---
title: "p8105_hw2_ar4459"
author: "ASHLEY ROMO"
date: "2023-10-04"
output: github_document
---


```{r}
library(tidyverse)
library(readxl)
```

## Problem 1

```{r clean_538_pols}
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read_csv("data/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez")) 
```



```{r clean_538_snp}
snp = 
  read_csv("data/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 
```

Finally, we tidy the `unemployment` data so that it can be merged with the `pols` and `snp` datasets.

```{r clean_538_unemp}
unemployment = 
  read_csv("data/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

Now we merge the three datasets!

```{r merge_538}
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)

str(data_538)
```

##2 

```{r}
mr_wheel_df =
  read_xlsx("data/202309 Trash Wheel Collection Data.xlsx", 1, range = "A2:N587") |> 
  janitor::clean_names()|> 
  drop_na(dumpster) |> 
  mutate(homes_powered = (weight_tons)*500/30,
         mr_trash = "Mr. Trash Wheel",
         year = as.numeric(year)
    ) |> 
  select(dumpster, month, year, date, weight = weight_tons, volume = volume_cubic_yards, everything()) 


prof_wheel_df =
  read_xlsx("data/202309 Trash Wheel Collection Data.xlsx",2 , range = "A2:M109") |> 
  janitor::clean_names()|> 
  drop_na(dumpster) |> 
  mutate(homes_powered = (weight_tons)*500/30,
         prof_trash = "Professor Trash Wheel"
    ) |> 
  select(dumpster, month, year, date, weight = weight_tons, volume = volume_cubic_yards, everything()) 


gwyn_wheel_df =
  read_xlsx("data/202309 Trash Wheel Collection Data.xlsx",4 , range = "A2:L159") |> 
  janitor::clean_names()|> 
  mutate(homes_powered = (weight_tons)*500/30,
         gwyn_trash = "Gwynnda Trash Wheel"
    ) |> 
  drop_na(dumpster) |> 
  select(dumpster, month, year, date, weight = weight_tons, volume = volume_cubic_yards, everything())

```



